#!/bin/bash
# File: build_package
# Editor: PyCharm
# Author: Austin (From Chengdu.China) https://fairy.host
# HomePage: https://github.com/AustinFairyland
# OS: Linux Ubuntu 22.04.4 Kernel 6.2.0-36-generic 
# CreatedTime: 2024/1/7

pip install setuptools wheel -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install --upgrade setuptools wheel -i https://pypi.tuna.tsinghua.edu.cn/simple
python setup.py sdist bdist_wheel
